# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.
provider "aws" {

  region = "us-west-2"


  assume_role {
    role_arn = "arn:aws:iam::732052188396:role/tfe-idseq"
  }

  allowed_account_ids = [732052188396]
}
# Aliased Providers (for doing things in every region).


provider "aws" {
  alias  = "us-west-2"
  region = "us-west-2"


  assume_role {
    role_arn = "arn:aws:iam::732052188396:role/tfe-idseq"
  }

  allowed_account_ids = [732052188396]
}


provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"


  assume_role {
    role_arn = "arn:aws:iam::732052188396:role/tfe-idseq"
  }

  allowed_account_ids = [732052188396]
}

terraform {
  required_version = "=1.3.6"

  backend "remote" {

    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces {
      name = "staging-individual-attr"
    }

  }
  required_providers {

    archive = {
      source = "hashicorp/archive"

      version = "~> 2.0"

    }

    aws = {
      source = "hashicorp/aws"

      version = "3.48.0"

    }

    local = {
      source = "hashicorp/local"

      version = "~> 2.0"

    }

    null = {
      source = "hashicorp/null"

      version = "~> 3.0"

    }

    random = {
      source = "hashicorp/random"

      version = "~> 2.2"

    }

    template = {
      source = "hashicorp/template"

      version = "~> 2.2"

    }

    tls = {
      source = "hashicorp/tls"

      version = "~> 3.0"

    }

  }
}
variable "env" {
  type    = string
  default = "staging"
}
variable "project" {
  type    = string
  default = "idseq"
}
variable "region" {
  type    = string
  default = "us-west-2"
}
variable "component" {
  type    = string
  default = "individual-attr"
}
variable "owner" {
  type    = string
  default = "biohub-tech@chanzuckerberg.com"
}
variable "tags" {
  type = object({ project : string, env : string, service : string, owner : string, managedBy : string })
  default = {
    project   = "idseq"
    env       = "staging"
    service   = "individual-attr"
    owner     = "biohub-tech@chanzuckerberg.com"
    managedBy = "terraform"
  }
}
variable "alignment_index_date" {
  type    = string
  default = "2021-01-22"
}
variable "build_index_date" {
  type    = string
  default = "2021-01-22"
}
variable "project_v1" {
  type    = string
  default = "czid"
}
variable "s3_bucket_aegea_ecs_execute" {
  type    = string
  default = "aegea-ecs-execute-staging"
}
variable "s3_bucket_idseq_bench" {
  type    = string
  default = "idseq-bench"
}
variable "s3_bucket_public_references" {
  type    = string
  default = "idseq-public-references"
}
variable "s3_bucket_samples" {
  type    = string
  default = "idseq-samples-staging"
}
variable "s3_bucket_samples_v1" {
  type    = string
  default = "czi-infectious-disease-staging-samples"
}
variable "s3_bucket_secrets" {
  type    = string
  default = "idseq-secrets"
}
variable "s3_bucket_workflows" {
  type    = string
  default = "idseq-workflows"
}
data "terraform_remote_state" "global" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces = {
      name = "global"
    }

  }
}
data "terraform_remote_state" "auth0" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces = {
      name = "staging-auth0"
    }

  }
}
data "terraform_remote_state" "batch" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces = {
      name = "staging-batch"
    }

  }
}
data "terraform_remote_state" "cloud-env" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces = {
      name = "staging-cloud-env"
    }

  }
}
data "terraform_remote_state" "db" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces = {
      name = "staging-db"
    }

  }
}
data "terraform_remote_state" "downloads" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces = {
      name = "staging-downloads"
    }

  }
}
data "terraform_remote_state" "ecs" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces = {
      name = "staging-ecs"
    }

  }
}
data "terraform_remote_state" "elasticsearch" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces = {
      name = "staging-elasticsearch"
    }

  }
}
data "terraform_remote_state" "elb-access-logs" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces = {
      name = "staging-elb-access-logs"
    }

  }
}
data "terraform_remote_state" "grafana" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces = {
      name = "staging-grafana"
    }

  }
}
data "terraform_remote_state" "heatmap-optimization" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces = {
      name = "staging-heatmap-optimization"
    }

  }
}
data "terraform_remote_state" "redis" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces = {
      name = "staging-redis"
    }

  }
}
data "terraform_remote_state" "resque" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces = {
      name = "staging-resque"
    }

  }
}
data "terraform_remote_state" "web" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces = {
      name = "staging-web"
    }

  }
}
data "terraform_remote_state" "idseq-dev" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "idseq-infra"
    workspaces = {
      name = "accounts-idseq-dev"
    }

  }
}
variable "aws_accounts" {
  type = map(any)
  default = {

    idseq-dev = 732052188396

    idseq-prod = 745463180746

  }
}
