variable "agent_tag" {
  type        = string
  description = "Tag to use for datadog agent image"
  default     = "7.53.0"
}

variable "eks_cluster_id" {
  type        = string
  description = "EKS cluster ID"
}

variable "api_key" {
  type        = string
  description = "A datadog api key to enable the datadog agent on the instance"
}

variable "namespace" {
  type        = string
  description = "The namespace to deploy datadog to"
}

variable "priority_class" {
  type        = string
  description = "The name of the priority class to use for datadog pods"
}

variable "ops_genie_owner_team" {
  type        = string
  description = "The name of the ops genie team to assign to datadog alerts"
}

variable "mute_dd_alerts" {
  type        = bool
  description = "Whether to mute datadog alerts"
  default     = true
}

variable "monitor_app_names" {
  type = object({
    external_dns = optional(string, "external_dns")
    alb_ingress  = optional(string, "aws_alb_ingress_controller")
    fluentbit    = optional(string, "fluentbit")
  })
  description = "The names of apps we want to monitor."
  default = {
  }
}

variable "tags" {
  description = "Standard tags. Typically generated by fogg"
  type = object({
    env : string,
    owner : string,
    project : string,
    service : string,
    managedBy : string,
  })
}