# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "sentry" {
  source       = "../../../modules/sentry"
  env          = local.env
  organization = local.organization
  owner        = local.owner
  project      = local.project



}
