# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "azs" {
  value     = module.aws-env-v4.0.0.azs
  sensitive = false
}

output "bastion_configuration" {
  value     = module.aws-env-v4.0.0.bastion_configuration
  sensitive = false
}

output "database_route_table_ids" {
  value     = module.aws-env-v4.0.0.database_route_table_ids
  sensitive = false
}

output "database_subnet_group" {
  value     = module.aws-env-v4.0.0.database_subnet_group
  sensitive = false
}

output "database_subnets" {
  value     = module.aws-env-v4.0.0.database_subnets
  sensitive = false
}

output "database_subnets_cidr_blocks" {
  value     = module.aws-env-v4.0.0.database_subnets_cidr_blocks
  sensitive = false
}

output "default_route_table_id" {
  value     = module.aws-env-v4.0.0.default_route_table_id
  sensitive = false
}

output "elasticache_route_table_ids" {
  value     = module.aws-env-v4.0.0.elasticache_route_table_ids
  sensitive = false
}

output "elasticache_subnet_group" {
  value     = module.aws-env-v4.0.0.elasticache_subnet_group
  sensitive = false
}

output "elasticache_subnets" {
  value     = module.aws-env-v4.0.0.elasticache_subnets
  sensitive = false
}

output "elasticache_subnets_cidr_blocks" {
  value     = module.aws-env-v4.0.0.elasticache_subnets_cidr_blocks
  sensitive = false
}

output "igw_id" {
  value     = module.aws-env-v4.0.0.igw_id
  sensitive = false
}

output "intra_route_table_ids" {
  value     = module.aws-env-v4.0.0.intra_route_table_ids
  sensitive = false
}

output "nat_ids" {
  value     = module.aws-env-v4.0.0.nat_ids
  sensitive = false
}

output "nat_public_ips" {
  value     = module.aws-env-v4.0.0.nat_public_ips
  sensitive = false
}

output "natgw_ids" {
  value     = module.aws-env-v4.0.0.natgw_ids
  sensitive = false
}

output "private_route_table_ids" {
  value     = module.aws-env-v4.0.0.private_route_table_ids
  sensitive = false
}

output "private_subnets" {
  value     = module.aws-env-v4.0.0.private_subnets
  sensitive = false
}

output "private_subnets_cidr_blocks" {
  value     = module.aws-env-v4.0.0.private_subnets_cidr_blocks
  sensitive = false
}

output "public_route_table_ids" {
  value     = module.aws-env-v4.0.0.public_route_table_ids
  sensitive = false
}

output "public_subnets" {
  value     = module.aws-env-v4.0.0.public_subnets
  sensitive = false
}

output "public_subnets_cidr_blocks" {
  value     = module.aws-env-v4.0.0.public_subnets_cidr_blocks
  sensitive = false
}

output "redshift_route_table_ids" {
  value     = module.aws-env-v4.0.0.redshift_route_table_ids
  sensitive = false
}

output "redshift_subnet_group" {
  value     = module.aws-env-v4.0.0.redshift_subnet_group
  sensitive = false
}

output "redshift_subnets" {
  value     = module.aws-env-v4.0.0.redshift_subnets
  sensitive = false
}

output "redshift_subnets_cidr_blocks" {
  value     = module.aws-env-v4.0.0.redshift_subnets_cidr_blocks
  sensitive = false
}

output "vgw_id" {
  value     = module.aws-env-v4.0.0.vgw_id
  sensitive = false
}

output "vpc_cidr_block" {
  value     = module.aws-env-v4.0.0.vpc_cidr_block
  sensitive = false
}

output "vpc_id" {
  value     = module.aws-env-v4.0.0.vpc_id
  sensitive = false
}


