# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "tfe" {
  source                    = "git@github.com:chanzuckerberg/shared-infra//terraform/modules/tfe-management/?ref=tfe-management-v3.2.0"
  accounts                  = local.accounts
  auto_apply                = local.auto_apply
  default_branch            = local.default_branch
  default_terraform_version = local.default_terraform_version
  envs                      = local.envs
  organization              = local.organization
  repo                      = local.repo
  tags                      = local.tags
  teams_with_write_access   = local.teams_with_write_access



}
