# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "dashboard" {
  value     = module.happy.dashboard
  sensitive = false
}

output "databases" {
  value     = module.happy.databases
  sensitive = true
}

output "integration_secret" {
  value     = module.happy.integration_secret
  sensitive = true
}

output "namespace" {
  value     = module.happy.namespace
  sensitive = false
}


