name: CypherID Web Infra Deploy
run-name: Deploy CypherID Web Infra to ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to which to deploy'
        required: true
        type: string
        default: 'dev'

env:
  AWS_REGION : us-west-2
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  DEPLOYMENT_ENVIRONMENT: ${{ inputs.environment }}

permissions:
  id-token: write
  contents: read

jobs:
  DeployTerraform:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::941377154785:role/gha-cypherid-workflow-infra-terraform
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Set up runner
        run: source scripts/init_ci_runner.sh
      - name: Terraform Init
        run: |
          cd terraform/envs/${{ env.DEPLOYMENT_ENVIRONMENT }}
          terraform -chdir=cloud-env init
      - name: Terraform Plan
        run: |
          cd terraform/envs/${{ env.DEPLOYMENT_ENVIRONMENT }}
          terraform -chdir=cloud-env plan